import Image from 'next/image'
import styles from './page.module.css';
import Head from 'next/head';
import { Share } from '@capacitor/share';
import { useSession } from 'next-auth/react';
import { MainPage } from './components/MainPage/MainPage';

export default function Home() {

  const share = async () => {
		await Share.share({
			title: 'Simons YT Channel',
			text: 'Learn to build awesome mobile apps!',
			url: 'https://www.youtube.com/simongrimmdev_',
			dialogTitle: 'Share with friends'
		});
	};

  return (
    <div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Well to Main Page
				</h1>
				<MainPage />
				
			</main>
		</div>
  )
}
